# Generated by Django 5.1.3 on 2025-01-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=50)),
                ('provider_address', models.CharField(max_length=100)),
                ('provider_phone_number', models.CharField(max_length=15)),
                ('provider_email', models.EmailField(max_length=254)),
                ('provider_account_no', models.PositiveIntegerField()),
                ('provider_ifsc_code', models.CharField(max_length=50)),
                ('provider_bannk_name', models.CharField(max_length=50)),
                ('provider_bank_branch', models.CharField(max_length=50)),
                ('provider_gst_no', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=50)),
                ('client_address', models.CharField(max_length=100)),
                ('client_phone_number', models.CharField(max_length=15)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_account_no', models.PositiveIntegerField()),
                ('client_ifsc_code', models.CharField(max_length=50)),
                ('client_bannk_name', models.CharField(max_length=50)),
                ('client_bank_branch', models.CharField(max_length=50)),
                ('client_gst_no', models.CharField(max_length=50)),
            ],
        ),
    ]
